
logging:
  level:
    root: info
    com.batchproject.springbatch: info

spring:
  batch:
    job:
      #enabled: false
      name: ${job.name:NONE}
    jdbc:
      initialize-schema: always
    datasource:
      url: jdbc:mariadb://localhost:3306/first
      driver-class-name: org.mariadb.jdbc.Driver
      username: user01
      password: user01
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
         format_sql: true
