

spring:
  main:
    web-application-type: none
  batch:
    jdbc:
      initialize-schema: "embedded"
  datasource:
    url: jdbc:mysql://localhost:3306/second?allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user02
    password: user02
