
spring:
  main:
    web-application-type: none
  batch:
    jdbc:
      initialize-schema: "always"
  datasource:
    url: jdbc:mysql://localhost:3306/second?allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user02
    password: user02
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        format_sql: true

