
spring.batch.job.names: ${job.name:NONE}

spring:
  #main:
  #  web-application-type: none
  batch:
    jdbc:
      initialize-schema: "always"
  datasource:
    url: jdbc:mysql://localhost:3306/second?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user02
    password: user02
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
