custom:
  task:
    name: ${name:NONE}
    properties: ${properties:NONE}
    argument: ${argument:NONE}
    cronschedule: ${cronschedule:5 * * * * ?}  #예_평일 오후 2시에 1번 실행  0 0 14 ? * MON-FRI *

spring:
  quartz:
    job-store-type: "jdbc"
    jdbc:
      initialize-schema: "always"
  main:
    web-application-type: none
  batch:
    jdbc:
      initialize-schema: "always"
   #job:
    #  enabled: false
    #  names: ${job.name:NONE}
  datasource:
    url: jdbc:mysql://localhost:3306/second?allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user02
    password: user02





